services:
  app:
    build: .
    environment:
      - SUPABASE_URL=${{ secrets.SUPABASE_URL }}
      - SUPABASE_ANON_KEY=${{ secrets.SUPABASE_ANON_KEY }}
      - SUPABASE_SERVICE_KEY=${{ secrets.SUPABASE_SERVICE_KEY }}
      - OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
      - SECRET_KEY=${{ secrets.SECRET_KEY }}
      - N8N_BASIC_AUTH_PASSWORD=${{ secrets.N8N_PASSWORD }}
    ports:
      - "8000:8000"
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  n8n:
    image: n8nio/n8n
    environment:
      - N8N_BASIC_AUTH_PASSWORD=${{ secrets.N8N_PASSWORD }}
    ports:
      - "5678:5678"
